/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QrAttendanceRouteImport } from './routes/qr-attendance'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as FaceAttendanceRouteImport } from './routes/face-attendance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QrAttendanceRoute = QrAttendanceRouteImport.update({
  id: '/qr-attendance',
  path: '/qr-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const FaceAttendanceRoute = FaceAttendanceRouteImport.update({
  id: '/face-attendance',
  path: '/face-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/face-attendance': typeof FaceAttendanceRoute
  '/faculty': typeof FacultyRoute
  '/qr-attendance': typeof QrAttendanceRoute
  '/reports': typeof ReportsRoute
  '/sessions': typeof SessionsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/face-attendance': typeof FaceAttendanceRoute
  '/faculty': typeof FacultyRoute
  '/qr-attendance': typeof QrAttendanceRoute
  '/reports': typeof ReportsRoute
  '/sessions': typeof SessionsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/face-attendance': typeof FaceAttendanceRoute
  '/faculty': typeof FacultyRoute
  '/qr-attendance': typeof QrAttendanceRoute
  '/reports': typeof ReportsRoute
  '/sessions': typeof SessionsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/face-attendance'
    | '/faculty'
    | '/qr-attendance'
    | '/reports'
    | '/sessions'
    | '/students'
    | '/subjects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/face-attendance'
    | '/faculty'
    | '/qr-attendance'
    | '/reports'
    | '/sessions'
    | '/students'
    | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/face-attendance'
    | '/faculty'
    | '/qr-attendance'
    | '/reports'
    | '/sessions'
    | '/students'
    | '/subjects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  DashboardRoute: typeof DashboardRoute
  FaceAttendanceRoute: typeof FaceAttendanceRoute
  FacultyRoute: typeof FacultyRoute
  QrAttendanceRoute: typeof QrAttendanceRoute
  ReportsRoute: typeof ReportsRoute
  SessionsRoute: typeof SessionsRoute
  StudentsRoute: typeof StudentsRoute
  SubjectsRoute: typeof SubjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-attendance': {
      id: '/qr-attendance'
      path: '/qr-attendance'
      fullPath: '/qr-attendance'
      preLoaderRoute: typeof QrAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/face-attendance': {
      id: '/face-attendance'
      path: '/face-attendance'
      fullPath: '/face-attendance'
      preLoaderRoute: typeof FaceAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  DashboardRoute: DashboardRoute,
  FaceAttendanceRoute: FaceAttendanceRoute,
  FacultyRoute: FacultyRoute,
  QrAttendanceRoute: QrAttendanceRoute,
  ReportsRoute: ReportsRoute,
  SessionsRoute: SessionsRoute,
  StudentsRoute: StudentsRoute,
  SubjectsRoute: SubjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
